### ISSUE TITLE
Use :reload-strategy :full

### ISSUE THREAD

**Issue by yenda** [flexsurfer/rn-shadow-steroid#1]
In latest version of shadow-cljs you now have the `:reload-strategy` :full in :devetools which should simplify your hot-reloading

**Comment by flexsurfer** [comment]
hey thanks, could you elaborate on how it can be used? where I can read more about it? thanks!

**Comment by flexsurfer** [comment]
oh, do you mean I don't need to use macros? mhm, but it doesn't simplify much

**Comment by flexsurfer** [comment]
btw i found this issue  https://github.com/thheller/shadow-cljs/issues/349 for context

**Comment by yenda** [comment]
yeah you don't need macro and counters with that.

Basically you can do:

```
(defonce component-to-update (atom nil))

(def updatable-root
  (with-meta root
    {:component-did-mount
     (fn [props]
       (this-as ^js this
         (reset! component-to-update this)))}))

(defn reload
  []
  (.forceUpdate ^js @component-to-update))
```

where updatable-root is the component you register like this in your init:
`(.registerComponent ^js react/app-registry "app-name" #(r/reactify-component updatable-root))`

you could also detect debug there and use your root directly when not in dev

**Comment by flexsurfer** [comment]
honestly, this looks more complicated than current implementation, we need to mess with the root component lifecycle and `this` , can't see the advantages of this approach yet. What i like in counter it can be used in prod as well because it's just empty atom called once in root function, but the anonymous wrapper function is not cool though

**Comment by yenda** [comment]
I don't see how it's more complicated. Anyway are you sure the atom solution is working when you make changes on any screen? I had an issue where it would only work for top level route changes. With full-reload no issues. I still think this approach is simpler: the library could provide a register-component function, and root component would only be messed with in dev

**Comment by flexsurfer** [comment]
> Anyway are you sure the atom solution is working when you make changes on any screen? 

code reload and update component approaches  are not related, i mean it doesn't matter if you use atom solution or .forceUpdate , reagent will update the root component in the same way
so if update works with atom it will work with forceUpdate and vice versa 

the problem with code reload happens when you pass render function as a parameter in ns which wont be reloaded , in that case this renderer function will be with old code , thats why i used macro, because root namespace always reloaded when you change any ns in the app, if you change ns which doesn't lead to root ns reload, hot reload wont  work for this ns, but i don't know how it can be done, but porbably there is a way, so using :full most robust solutions probably  , but still can be used with current atom implementation 

> only be messed with in dev

whats the best way to detect if it's dev ?

**Comment by yenda** [comment]
At status we were using  :closure-defines   ` {"goog.DEBUG" false}` in prod and doing `when js/goog.DEBUG` checks in code. I think it's even eliminated with advanced compilation
